# Generated by Django 4.2.6 on 2023-11-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
